IMAGE_KEY_HEADER_GOLD 							= "res/image/common/header_gold.png"--[[银两]]
IMAGE_KEY_HEADER_TILI 							= "res/image/common/header_tili.png"--[[体力]]
IMAGE_KEY_HEADER_INGOT 							= "res/image/common/header_ingot.png"--[[元宝]]
IMAGE_KEY_HEADER_FEICUI							= "res/image/common/header_feicui.png"--[[翡翠]]
IMAGE_KEY_HEADER_ENERGY							= "res/image/common/header_energy.png"--[[精力]]
IMAGE_KEY_HEADER_CONTRIBUTION					= "res/image/common/header_contribution.png"--[[贡献]]
IMAGE_KEY_HEADER_AWARD							= "res/image/common/header_award.png"--[[奖牌]]
IMAGE_KEY_HEADER_SAINTSTONE						= "res/image/common/header_saintstone.png"--[[神石]]
IMAGE_KEY_HEADER_SERVANTSTONE                   = "res/image/common/header_wanglingpo.png" --[[万灵魂]]
IMAGE_KEY_HEADER_REDJADE						= "res/image/common/header_redjade.png"--[[血玉]]
IMAGE_KEY_HEADER_HONOR							= "res/image/common/task_rmb_honor2.png" --荣誉
IMAGE_KEY_HEADER_SMELT 							= "res/image/common/header_smelt.png" --回收点数
IMAGE_KEY_HEADER_PRESTIGE 						= "res/image/plugin/competitive_layer/competitiveDefense_Prestige.png" --威望
IMAGE_KEY_HEADER_PRESTIGE_SMALL					= "res/image/common/header_prestige.png" --威望小
IMAGE_KEY_HEADER_POWER 							= "res/image/common/fightValue_Image.png" --战力
IMAGE_KEY_HEADER_OFFERREWARD					= "res/image/offerReward/offerReward02.png" --悬赏奖牌
IMAGE_KEY_HEADER_BLOOD 							= "res/image/common/header_blood.png" -- 修罗血
IMAGE_KEY_HEADER_CONTRI 						= "res/image/common/header_contri.png" -- 帮派贡献
IMAGE_KEY_HEADER_FLOWER 						= "res/image/plugin/weaponshop/hua.png" -- 鲜花
IMAGE_KEY_HEADER_PSYCHICSTONE					= "res/image/exchange/exchange_diamond.png" -- 召唤石
IMAGE_KEY_HEADER_SHENJIANG                      = "res/image/common/sjxwicon1.png"     --神将信物
IMAGE_KEY_HEADER_SOUL                           = "res/image/common/header_soul.png" --魂玉
IMAGE_KEY_HEADER_LOCKYCOIN                      = "res/image/common/header_luck.png" --[[幸运币]]
IMAGE_KEY_HEADER_ZHENQI		                    = "res/image/common/header_zhenqi.png" --[[真气]]
IMAGE_KEY_HEADER_SOULG                         = "res/image/common/header_soul.png" --绿魂石
IMAGE_KEY_HEADER_SOULB                         = "res/image/common/header_soul.png" --蓝魂石
IMAGE_KEY_HEADER_SOULP                         = "res/image/common/header_soul.png" --紫魂石
IMAGE_KEY_HEADER_SOULR                         = "res/image/common/header_soul.png" --红魂石
IMAGE_KEY_HEADER_REFRESHORDER 					= "res/image/common/icon_shuaxin.png"--[[刷新令]]


IMAGE_KEY_COMMON_ITEM_ENERGY					= "res/image/common/common_item_energy.png"
IMAGE_KEY_COMMON_ITEM_FEICUI					= "res/image/common/common_item_feicui.png"
IMAGE_KEY_COMMON_ITEM_INGOT						= "res/image/common/common_item_ingot.png"
IMAGE_KEY_COMMON_ITEM_TILI						= "res/image/common/common_item_tili.png"
IMAGE_KEY_COMMON_ITEM_GOLD						= "res/image/common/common_item_gold.png"--[[道具银两]]
IMAGE_KEY_COMMON_ITEM_EXP						= "res/image/common/common_item_exp.png"--[[经验暂时用这个 目前没有HEADER的]]
IMAGE_KEY_COMMON_ITEM_HONOR						= "res/image/common/common_item_honor.png"--[[荣誉暂时先用这个……]]
IMAGE_KEY_COMMON_ITEM_CERULEANDRAGON			= "res/image/common/beast_azure.png"--[[青龙暂定]]
IMAGE_KEY_COMMON_ITEM_WHITETIGER				= "res/image/common/beast_white.png"--[[白虎暂定]]
IMAGE_KEY_COMMON_ITEM_VINACEOUSROSEFINCH		= "res/image/common/beast_vermilion.png"--[[朱雀暂定]]
IMAGE_KEY_COMMON_ITEM_DRAGONTORTOISE			= "res/image/common/beast_black.png"--[[玄武暂定]]
IMAGE_KEY_COMMON_ITEM_SAINTSTONE				= "res/image/common/common_item_saintstone.png"--[[神石]]
IMAGE_KEY_COMMON_ITEM_SERVANTSTONE				= "res/image/common/common_item_wanglingpo.png"--[[万灵魂]]
IMAGE_KEY_COMMON_ITEM_AWARD 					= "res/image/common/common_item_award.png"--[[奖牌]]
IMAGE_KEY_COMMON_ITEM_PRESTIGE 					= "res/image/common/common_item_prestige.png"--[[声望/威望]]
IMAGE_KEY_COMMON_ITEM_SMELTPOINT 				= "res/image/common/common_item_smelt.png"--[[回收点数]]
IMAGE_KEY_COMMON_ITEM_BOUNTY   				    = "res/image/common/common_item_bounty.png"--[[悬赏令牌]]
IMAGE_KEY_COMMON_ITEM_HEROEXP					= "res/image/common/common_hero_exp.png" --[[英雄经验]]
IMAGE_KEY_COMMON_ITEM_CONTRI					= "res/image/common/common_item_contri.png" --[[帮派贡献]]
IMAGE_KEY_COMMON_ITEM_FLOWER					= "res/image/common/common_item_flower.png" --[[鲜花]]
IMAGE_KEY_COMMON_ITEM_BLOOD						= "res/image/common/common_item_blood.png"--[[修罗血]]
IMAGE_KEY_COMMON_LIGHT_STAR                     = "res/image/common/star_light.png"    --[[星星]]
IMAGE_KEY_COMMON_ITEM_SOUL                      = "res/image/common/common_item_soul.png"--[[魂玉]]
IMAGE_KEY_COMMON_ITEM_LOCKYCOIN					= "res/image/common/common_item_luck.png"--[[幸运币]]
IMAGE_KEY_COMMON_ITEM_CITYEXP 					= "res/image/common/common_item_cityHonor.png"--[[种族城市经验]]
IMAGE_KEY_COMMON_ITEM_ZHENQI 					= "res/image/common/common_item_zhenqi.png"--[[真气]]
IMAGE_KEY_COMMON_ITEM_QLY                       ="res/image/common/Servant_qly.png"  --[[侍仆·千鸟樱]]
IMAGE_KEY_COMMON_ITEM_QCJ                       ="res/image/common/Servant_qcj.png"  --[[侍仆·浅仓镜]]
IMAGE_KEY_COMMON_ITEM_YLY                       ="res/image/common/Servant_yly.png"  --[[侍仆·亚里亚]]
IMAGE_KEY_COMMON_ITEM_MSY                       ="res/image/common/Servant_msy.png"  --[[侍仆·麻神一]]
IMAGE_KEY_COMMON_ITEM_QZL                       ="res/image/common/Servant_qzl.png"  --[[侍仆·青佐木]]

---authored by LITAO ,directory
IMAGE_KEY_CHATROOM_RES_PATH						= "res/image/chatroom/" --聊天资源路径
IMAGE_KEY_CAMP_RES_PATH							= "res/image/camp/" --种族资源路径
IMAGE_KEY_ANNOUNCEMENT_BACK						= "res/image/chatroom/chatroom_ann_back.png" --主城建筑里产出的又有银两又有翡翠
IMAGE_KEY_LOGIN_BG								= "res/image/login/login_bg.jpg"
