requires("src/gui/XTHDCheckBox.lua")
requires("src/gui/XTHD/XTHDDialog.lua")
requires("src/gui/XTHD/XTHDImage.lua")
requires("src/gui/XTHD/XTHDLabel.lua")
requires("src/gui/XTHD/XTHDPushButton.lua")
requires("src/gui/XTHD/XTHDSprite.lua")
requires("src/gui/XTHD/XTHDRichLabelTTF.lua")
requires("src/gui/XTHD/XTHDTouchExtend.lua")
requires("src/gui/XTHDToast.lua")
requires("src/gui/GuiCommon.lua")
requires("src/gui/ClipNode.lua")
requires("src/gui/XTHDPopLayer.lua")
requires("src/gui/XTHDConfirmDialog.lua")
-- requires("src/fsgl/layer/common/HeroIntroduceLayer.lua")
requires("src/gui/XTHDMarqueeNode.lua")
