GodsRoad = {
    {
        ["id"] = 1,
        ["taskname"] = "等级",
        ["description"] = "等级达到30级即可领取",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 30,
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 2,
        ["taskname"] = "赏金",
        ["description"] = "参加赏金猎人2次",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 2,
        ["gotype"] = 3,
        ["goparam"] = 0,
        ["needtype"] = 38,
        ["taskparam"] = 2,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 3,
        ["taskname"] = "赏金",
        ["description"] = "参加赏金猎人5次",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 2,
        ["gotype"] = 3,
        ["goparam"] = 0,
        ["needtype"] = 38,
        ["taskparam"] = 5,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 4,
        ["taskname"] = "赏金",
        ["description"] = "参加赏金猎人8次",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 2,
        ["gotype"] = 3,
        ["goparam"] = 0,
        ["needtype"] = 38,
        ["taskparam"] = 8,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 5,
        ["taskname"] = "赏金",
        ["description"] = "参加赏金猎人12次",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 2,
        ["gotype"] = 3,
        ["goparam"] = 0,
        ["needtype"] = 38,
        ["taskparam"] = 12,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 6,
        ["taskname"] = "赏金",
        ["description"] = "参加赏金猎人15次",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 2,
        ["gotype"] = 3,
        ["goparam"] = 0,
        ["needtype"] = 38,
        ["taskparam"] = 15,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 7,
        ["taskname"] = "悬赏",
        ["description"] = "进行3次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "3#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 50000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 8,
        ["taskname"] = "悬赏",
        ["description"] = "进行6次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "6#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 50000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 9,
        ["taskname"] = "悬赏",
        ["description"] = "进行12次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "12#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 50000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 10,
        ["taskname"] = "悬赏",
        ["description"] = "进行18次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "18#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 50000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 11,
        ["taskname"] = "悬赏",
        ["description"] = "进行24次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "24#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 12,
        ["taskname"] = "悬赏",
        ["description"] = "进行30次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "30#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 13,
        ["taskname"] = "悬赏",
        ["description"] = "进行40次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "40#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 14,
        ["taskname"] = "悬赏",
        ["description"] = "进行50次悬赏任务",
        ["info"] = "第一天",
        ["day"] = 1,
        ["tagpart"] = 3,
        ["gotype"] = 47,
        ["goparam"] = 0,
        ["needtype"] = 21,
        ["taskparam"] = "50#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 15,
        ["taskname"] = "等级",
        ["description"] = "等级达到35",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 35,
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 16,
        ["taskname"] = "多人",
        ["description"] = "参加1次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 1,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2210#2",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 17,
        ["taskname"] = "多人",
        ["description"] = "参加5次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 5,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2210#4",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 18,
        ["taskname"] = "多人",
        ["description"] = "参加10次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 10,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2210#6",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 19,
        ["taskname"] = "多人",
        ["description"] = "参加15次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 15,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#2",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 20,
        ["taskname"] = "多人",
        ["description"] = "参加20次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 20,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#4",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 21,
        ["taskname"] = "多人",
        ["description"] = "参加25次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 25,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#6",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 22,
        ["taskname"] = "多人",
        ["description"] = "参加30次多人副本",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 2,
        ["gotype"] = 60,
        ["goparam"] = 0,
        ["needtype"] = 20,
        ["taskparam"] = 30,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#8",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 23,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加运粮2次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 15,
        ["taskparam"] = 2,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 24,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加运粮4次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 15,
        ["taskparam"] = 4,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 25,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加运粮8次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 15,
        ["taskparam"] = 8,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 26,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加运粮12次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 15,
        ["taskparam"] = 12,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 27,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加运粮16次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 15,
        ["taskparam"] = 16,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 28,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加劫粮20次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 26,
        ["taskparam"] = 20,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 29,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加劫粮24次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 26,
        ["taskparam"] = 24,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 30,
        ["taskname"] = "运粮",
        ["description"] = "活动期间参加劫粮30次",
        ["info"] = "第二天",
        ["day"] = 2,
        ["tagpart"] = 3,
        ["gotype"] = 45,
        ["goparam"] = 0,
        ["needtype"] = 26,
        ["taskparam"] = 30,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 31,
        ["taskname"] = "等级",
        ["description"] = "等级达到40级",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 40,
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 32,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第2层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 2,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 33,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第4层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 4,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 34,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第6层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 6,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 35,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第8层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 8,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 36,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第10层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 10,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 37,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第12层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 12,
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 38,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第15层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 15,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 39,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第18层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 18,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#20",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 40,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第21层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 21,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#30",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 41,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第24层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 24,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#40",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 42,
        ["taskname"] = "试炼",
        ["description"] = "在活动期间通过通过试炼之塔第30层",
        ["info"] = "第三天",
        ["day"] = 3,
        ["tagpart"] = 2,
        ["gotype"] = 4,
        ["goparam"] = 0,
        ["needtype"] = 12,
        ["taskparam"] = 30,
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#50",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 43,
        ["taskname"] = "等级",
        ["description"] = "等级达到45级",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 45,
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 44,
        ["taskname"] = "招募",
        ["description"] = "拥有紫色以上品质英雄3个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "4#3",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 45,
        ["taskname"] = "招募",
        ["description"] = "拥有紫色以上品质英雄4个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "4#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 46,
        ["taskname"] = "招募",
        ["description"] = "拥有紫色以上品质英雄6个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "4#6",
        ["reward1type"] = 3,
        ["reward1param"] = 60,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 47,
        ["taskname"] = "招募",
        ["description"] = "拥有紫色以上品质英雄8个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "4#8",
        ["reward1type"] = 3,
        ["reward1param"] = 80,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 48,
        ["taskname"] = "招募",
        ["description"] = "拥有紫色以上品质英雄10个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "4#10",
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = 2,
        ["reward2param"] = 100000,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 49,
        ["taskname"] = "招募",
        ["description"] = "拥有橙色品质英雄1个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "5#1",
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = 4,
        ["reward2param"] = "81704#2",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 50,
        ["taskname"] = "招募",
        ["description"] = "拥有橙色品质英雄2个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "5#2",
        ["reward1type"] = 3,
        ["reward1param"] = 200,
        ["reward2type"] = 4,
        ["reward2param"] = "81704#3",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 51,
        ["taskname"] = "招募",
        ["description"] = "拥有橙色品质英雄3个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "5#3",
        ["reward1type"] = 3,
        ["reward1param"] = 400,
        ["reward2type"] = 4,
        ["reward2param"] = "81704#5",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 52,
        ["taskname"] = "招募",
        ["description"] = "拥有橙色品质英雄4个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "5#4",
        ["reward1type"] = 3,
        ["reward1param"] = 600,
        ["reward2type"] = 4,
        ["reward2param"] = "81704#8",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 53,
        ["taskname"] = "招募",
        ["description"] = "拥有橙色品质英雄5个",
        ["info"] = "第四天",
        ["day"] = 4,
        ["tagpart"] = 2,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 39,
        ["taskparam"] = "5#5",
        ["reward1type"] = 3,
        ["reward1param"] = 800,
        ["reward2type"] = 4,
        ["reward2param"] = "81704#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 54,
        ["taskname"] = "等级",
        ["description"] = "等级达到50级",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 1,
        ["gotype"] = 18,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 50,
        ["reward1type"] = 3,
        ["reward1param"] = 150,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 55,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至白银组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 2,
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 56,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至黄金组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 3,
        ["reward1type"] = 3,
        ["reward1param"] = 200,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#20",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 57,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至白金组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 4,
        ["reward1type"] = 3,
        ["reward1param"] = 300,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#30",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 58,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至钻石组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 5,
        ["reward1type"] = 3,
        ["reward1param"] = 400,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#40",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 59,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至大师组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 6,
        ["reward1type"] = 3,
        ["reward1param"] = 500,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#50",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 60,
        ["taskname"] = "竞技",
        ["description"] = "在活动期间排位赛晋级至宗师组",
        ["info"] = "第五天",
        ["day"] = 5,
        ["tagpart"] = 2,
        ["gotype"] = 25,
        ["goparam"] = 0,
        ["needtype"] = 28,
        ["taskparam"] = 7,
        ["reward1type"] = 3,
        ["reward1param"] = 600,
        ["reward2type"] = 4,
        ["reward2param"] = "2251#100",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 61,
        ["taskname"] = "等级",
        ["description"] = "等级达到55级",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 55,
        ["reward1type"] = 3,
        ["reward1param"] = 150,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 62,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行1次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "1#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 63,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行2次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "2#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 64,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行5次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "5#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 65,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行10次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "10#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 66,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行15次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "15#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 67,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行20次挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "20#3",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 68,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行1次紫色关卡挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "1#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 69,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行2次紫色关卡挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "2#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#30",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 70,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行5次紫色关卡挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "5#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#50",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 71,
        ["taskname"] = "天兵",
        ["description"] = "在天兵阁中进行10次紫色关卡挑战",
        ["info"] = "第六天",
        ["day"] = 6,
        ["tagpart"] = 2,
        ["gotype"] = 5,
        ["goparam"] = 0,
        ["needtype"] = 19,
        ["taskparam"] = "10#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#100",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 72,
        ["taskname"] = "等级",
        ["description"] = "等级达到60级",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 1,
        ["gotype"] = 0,
        ["goparam"] = 0,
        ["needtype"] = 4,
        ["taskparam"] = 60,
        ["reward1type"] = 3,
        ["reward1param"] = 150,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 73,
        ["taskname"] = "洗练",
        ["description"] = "任意洗练装备2次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "2#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 74,
        ["taskname"] = "洗练",
        ["description"] = "任意洗练装备5次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "5#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 75,
        ["taskname"] = "洗练",
        ["description"] = "任意洗练装备10次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "10#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 76,
        ["taskname"] = "洗练",
        ["description"] = "任意洗练装备20次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "20#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 77,
        ["taskname"] = "洗练",
        ["description"] = "任意洗练装备30次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "30#1",
        ["reward1type"] = 3,
        ["reward1param"] = 20,
        ["reward2type"] = nil,
        ["reward2param"] = nil,
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 78,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意紫色或以上品质的装备10次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "10#4",
        ["reward1type"] = 3,
        ["reward1param"] = 30,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 79,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意紫色或以上品质的装备20次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "20#4",
        ["reward1type"] = 3,
        ["reward1param"] = 50,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#20",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 80,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意紫色或以上品质的装备50次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "50#4",
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = 4,
        ["reward2param"] = "2243#50",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 81,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意橙色或以上品质的装备20次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "20#5",
        ["reward1type"] = 3,
        ["reward1param"] = 100,
        ["reward2type"] = 4,
        ["reward2param"] = "2244#10",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 82,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意橙色或以上品质的装备50次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "50#5",
        ["reward1type"] = 3,
        ["reward1param"] = 150,
        ["reward2type"] = 4,
        ["reward2param"] = "2244#30",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
    {
        ["id"] = 83,
        ["taskname"] = "洗练",
        ["description"] = "洗练任意橙色或以上品质的装备100次",
        ["info"] = "第七天",
        ["day"] = 7,
        ["tagpart"] = 2,
        ["gotype"] = 37,
        ["goparam"] = 0,
        ["needtype"] = 23,
        ["taskparam"] = "100#5",
        ["reward1type"] = 3,
        ["reward1param"] = 200,
        ["reward2type"] = 4,
        ["reward2param"] = "2244#60",
        ["reward3type"] = nil,
        ["reward3param"] = nil,
        ["reward4type"] = nil,
        ["reward4param"] = nil,
    },
}