LandReward={
	{
		["id"] = 1,
		["days"] = 1,
		["level"] = 15,
		["reword1type"] = 4,
		["reword1id"] = 2003,
		["reword1num"] = 10,
		["reword2type"] = 0,
		["reword2id"] = 0,
		["reword2num"] = 0,
		["reword3type"] = 0,
		["reword3id"] = 0,
		["reword3num"] = 0,
		["reword4type"] = 0,
		["reword4id"] = 0,
		["reword4num"] = 0,
	},
	{
		["id"] = 2,
		["days"] = 2,
		["level"] = 30,
		["reword1type"] = 4,
		["reword1id"] = 2003,
		["reword1num"] = 20,
		["reword2type"] = 0,
		["reword2id"] = 0,
		["reword2num"] = 0,
		["reword3type"] = 0,
		["reword3id"] = 0,
		["reword3num"] = 0,
		["reword4type"] = 0,
		["reword4id"] = 0,
		["reword4num"] = 0,
	},
	{
		["id"] = 3,
		["days"] = 3,
		["level"] = 35,
		["reword1type"] = 4,
		["reword1id"] = 2003,
		["reword1num"] = 30,
		["reword2type"] = 0,
		["reword2id"] = 0,
		["reword2num"] = 0,
		["reword3type"] = 0,
		["reword3id"] = 0,
		["reword3num"] = 0,
		["reword4type"] = 0,
		["reword4id"] = 0,
		["reword4num"] = 0,
	},
	{
		["id"] = 4,
		["days"] = 4,
		["level"] = 40,
		["reword1type"] = 4,
		["reword1id"] = 2003,
		["reword1num"] = 40,
		["reword2type"] = 0,
		["reword2id"] = 0,
		["reword2num"] = 0,
		["reword3type"] = 0,
		["reword3id"] = 0,
		["reword3num"] = 0,
		["reword4type"] = 0,
		["reword4id"] = 0,
		["reword4num"] = 0,
	},
	{
		["id"] = 5,
		["days"] = 5,
		["level"] = 45,
		["reword1type"] = 4,
		["reword1id"] = 2004,
		["reword1num"] = 50,
		["reword2type"] = 0,
		["reword2id"] = 0,
		["reword2num"] = 0,
		["reword3type"] = 0,
		["reword3id"] = 0,
		["reword3num"] = 0,
		["reword4type"] = 0,
		["reword4id"] = 0,
		["reword4num"] = 0,
	},
}