MenubarId = 
{
    { id = 1, systemName = "主线副本", functionid = 18, },
    { id = 2, systemName = "精英副本  ", functionid = 19, },
    { id = 3, systemName = "赏金猎人", functionid = 25, },
    { id = 4, systemName = "试炼之塔", functionid = 26, },
    { id = 5, systemName = "神兵阁", functionid = 27, },
    { id = 6, systemName = "神器遗迹", functionid = 23, },
    { id = 7, systemName = "万宝阁", functionid = 10, },
    { id = 8, systemName = "商城", functionid = 0, },
    { id = 9, systemName = "阵营商店兑换", functionid = 32, },
    { id = 10, systemName = "竞技场兑换", functionid = 33, },
    { id = 11, systemName = "回收兑换", functionid = 34, },
    { id = 12, systemName = "神器兑换  ", functionid = 35, },
    { id = 13, systemName = "体力购买", functionid = 36, },
    { id = 14, systemName = "元宝换银两", functionid = 37, },
    { id = 15, systemName = "元宝换翡翠 ", functionid = 38, },
    { id = 16, systemName = "装备系统", functionid = 39, },
    { id = 17, systemName = "回收系统", functionid = 29, },
    { id = 18, systemName = "援军降临", functionid = 8, },
    { id = 19, systemName = "神兵异宝", functionid = 8, },
    { id = 20, systemName = "活动界面", functionid = 41, },
    { id = 21, systemName = "至尊任务", functionid = 42, },
    { id = 22, systemName = "主线任务", functionid = 43, },
    { id = 23, systemName = "日常任务  ", functionid = 44, },
    { id = 24, systemName = "支线任务", functionid = 45, },
    { id = 25, systemName = "竞技场", functionid = 17, },
    { id = 26, systemName = "阵营捐献", functionid = 46, },
    { id = 27, systemName = "阵营战场", functionid = 47, },
    { id = 28, systemName = "阵营任务", functionid = 48, },
    { id = 29, systemName = "演武场", functionid = 7, },
    { id = 30, systemName = "万宝阁", functionid = 10, },
    { id = 31, systemName = "英雄-进阶", functionid = 49, },
    { id = 32, systemName = "装备-升星", functionid = 50, },
    { id = 33, systemName = "装备-强化", functionid = 51, },
    { id = 34, systemName = "英雄-升星", functionid = 52, },
    { id = 35, systemName = "神器系统", functionid = 24, },
    { id = 36, systemName = "英雄-升级技能", functionid = 53, },
    { id = 37, systemName = "装备-洗练", functionid = 54, },
    { id = 38, systemName = "英雄-升级", functionid = 55, },
    { id = 39, systemName = "七星坛英雄兑换", functionid = 56, },
    { id = 40, systemName = "七星坛装备兑换", functionid = 57, },
    { id = 41, systemName = "铁匠铺", functionid = 11, },
    { id = 42, systemName = "充值界面", functionid = 58, },
    { id = 43, systemName = "vip界面", functionid = 59, },
    { id = 44, systemName = "英雄界面", functionid = 49, },
    { id = 47, systemName = "悬赏任务", functionid = 71, },
    { id = 58, systemName = "趋吉避凶", functionid = 79, },
    { id = 60, systemName = "多人副本", functionid = 80, },
    { id = 62, systemName = "镜像之路", functionid = 87, },
    { id = 63, systemName = "修仙圣境", functionid = 86, },
    { id = 64, systemName = "日常商店", functionid = 84, },
    { id = 65, systemName = "限时商店", functionid = 74, },
    { id = 66, systemName = "多人副本", functionid = 80, },
    { id = 67, systemName = "帮派商店", functionid = 89, },
    { id = 68, systemName = "领地商店", functionid = 32, },
    { id = 69, systemName = "强化商店", functionid = 90, },
    { id = 70, systemName = "生命之树", functionid = 91, },
    { id = 71, systemName = "世界BOSS", functionid = 75, },
    { id = 72, systemName = "灵之神域", functionid = 88, },
    { id = 73, systemName = "鲜花商店", functionid = 92, },
    { id = 74, systemName = "修罗商店", functionid = 93, },
    { id = 75, systemName = "噩梦副本", functionid = 82, },
    { id = 76, systemName = "押运粮草", functionid = 76, },
    { id = 77, systemName = "献祭", functionid = 95, },
    { id = 78, systemName = "六六大顺", functionid = 68, },
    { id = 79, systemName = "帮派", functionid = 72, },
    { id = 80, systemName = "阵营捐献", functionid = 46, },
}

