PlayerHeadOn={
	{
		["id"] = 1,
		["typeA"] = 2,
		["resource"] = 1,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 1,
	},
	{
		["id"] = 2,
		["typeA"] = 2,
		["resource"] = 301,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 5,
	},
	{
		["id"] = 3,
		["typeA"] = 2,
		["resource"] = 302,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 10,
	},
	{
		["id"] = 4,
		["typeA"] = 2,
		["resource"] = 303,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 15,
	},
	{
		["id"] = 5,
		["typeA"] = 2,
		["resource"] = 304,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 20,
	},
	{
		["id"] = 6,
		["typeA"] = 2,
		["resource"] = 305,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 25,
	},
	{
		["id"] = 7,
		["typeA"] = 2,
		["resource"] = 306,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 30,
	},
	{
		["id"] = 8,
		["typeA"] = 2,
		["resource"] = 307,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 33,
	},
	{
		["id"] = 9,
		["typeA"] = 2,
		["resource"] = 308,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 35,
	},
	{
		["id"] = 10,
		["typeA"] = 2,
		["resource"] = 309,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 37,
	},
	{
		["id"] = 11,
		["typeA"] = 2,
		["resource"] = 310,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 39,
	},
	{
		["id"] = 12,
		["typeA"] = 2,
		["resource"] = 311,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 41,
	},
	{
		["id"] = 13,
		["typeA"] = 2,
		["resource"] = 312,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 43,
	},
	{
		["id"] = 14,
		["typeA"] = 2,
		["resource"] = 313,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 45,
	},
	{
		["id"] = 15,
		["typeA"] = 2,
		["resource"] = 314,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 47,
	},
	{
		["id"] = 16,
		["typeA"] = 2,
		["resource"] = 315,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 49,
	},
	{
		["id"] = 17,
		["typeA"] = 2,
		["resource"] = 316,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 51,
	},
	{
		["id"] = 18,
		["typeA"] = 2,
		["resource"] = 317,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 53,
	},
	{
		["id"] = 19,
		["typeA"] = 2,
		["resource"] = 318,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 55,
	},
	{
		["id"] = 20,
		["typeA"] = 2,
		["resource"] = 319,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 57,
	},
	{
		["id"] = 21,
		["typeA"] = 2,
		["resource"] = 320,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 59,
	},
	{
		["id"] = 22,
		["typeA"] = 2,
		["resource"] = 801,
		["word"] = nil,
		["typeB"] = 1,
		["condition"] = 61,
	},
	{
		["id"] = 23,
		["typeA"] = 4,
		["resource"] = 4,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 4,
	},
	{
		["id"] = 24,
		["typeA"] = 4,
		["resource"] = 5,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 5,
	},
	{
		["id"] = 25,
		["typeA"] = 4,
		["resource"] = 7,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 7,
	},
	{
		["id"] = 26,
		["typeA"] = 4,
		["resource"] = 8,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 8,
	},
	{
		["id"] = 27,
		["typeA"] = 4,
		["resource"] = 9,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 9,
	},
	{
		["id"] = 28,
		["typeA"] = 4,
		["resource"] = 12,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 12,
	},
	{
		["id"] = 29,
		["typeA"] = 4,
		["resource"] = 15,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 15,
	},
	{
		["id"] = 30,
		["typeA"] = 4,
		["resource"] = 17,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 17,
	},
	{
		["id"] = 31,
		["typeA"] = 4,
		["resource"] = 21,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 21,
	},
	{
		["id"] = 32,
		["typeA"] = 4,
		["resource"] = 25,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 25,
	},
	{
		["id"] = 33,
		["typeA"] = 4,
		["resource"] = 27,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 27,
	},
	{
		["id"] = 34,
		["typeA"] = 4,
		["resource"] = 28,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 28,
	},
	{
		["id"] = 35,
		["typeA"] = 4,
		["resource"] = 29,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 29,
	},
	{
		["id"] = 36,
		["typeA"] = 4,
		["resource"] = 30,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 30,
	},
	{
		["id"] = 37,
		["typeA"] = 4,
		["resource"] = 31,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 31,
	},
	{
		["id"] = 38,
		["typeA"] = 4,
		["resource"] = 32,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 32,
	},
	{
		["id"] = 39,
		["typeA"] = 4,
		["resource"] = 34,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 34,
	},
	{
		["id"] = 40,
		["typeA"] = 4,
		["resource"] = 35,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 35,
	},
	{
		["id"] = 41,
		["typeA"] = 4,
		["resource"] = 37,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 37,
	},
	{
		["id"] = 42,
		["typeA"] = 4,
		["resource"] = 40,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 40,
	},
	{
		["id"] = 43,
		["typeA"] = 4,
		["resource"] = 41,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 41,
	},
	{
		["id"] = 44,
		["typeA"] = 4,
		["resource"] = 46,
		["word"] = nil,
		["typeB"] = 3,
		["condition"] = 46,
	},
	{
		["id"] = 45,
		["typeA"] = 3,
		["resource"] = 1001,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 1,
	},
	{
		["id"] = 46,
		["typeA"] = 3,
		["resource"] = 1002,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 1,
	},
	{
		["id"] = 47,
		["typeA"] = 3,
		["resource"] = 1003,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 1,
	},
	{
		["id"] = 48,
		["typeA"] = 3,
		["resource"] = 1004,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 2,
	},
	{
		["id"] = 49,
		["typeA"] = 3,
		["resource"] = 1005,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 2,
	},
	{
		["id"] = 50,
		["typeA"] = 3,
		["resource"] = 1006,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 2,
	},
	{
		["id"] = 51,
		["typeA"] = 3,
		["resource"] = 1007,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 3,
	},
	{
		["id"] = 52,
		["typeA"] = 3,
		["resource"] = 1008,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 3,
	},
	{
		["id"] = 53,
		["typeA"] = 3,
		["resource"] = 1009,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 3,
	},
	{
		["id"] = 54,
		["typeA"] = 3,
		["resource"] = 1010,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 4,
	},
	{
		["id"] = 55,
		["typeA"] = 3,
		["resource"] = 1011,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 4,
	},
	{
		["id"] = 56,
		["typeA"] = 3,
		["resource"] = 1012,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 4,
	},
	{
		["id"] = 57,
		["typeA"] = 3,
		["resource"] = 1013,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 5,
	},
	{
		["id"] = 58,
		["typeA"] = 3,
		["resource"] = 1014,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 5,
	},
	{
		["id"] = 59,
		["typeA"] = 3,
		["resource"] = 1015,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 5,
	},
	{
		["id"] = 60,
		["typeA"] = 3,
		["resource"] = 1016,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 6,
	},
	{
		["id"] = 61,
		["typeA"] = 3,
		["resource"] = 1017,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 6,
	},
	{
		["id"] = 62,
		["typeA"] = 3,
		["resource"] = 1018,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 6,
	},
	{
		["id"] = 63,
		["typeA"] = 3,
		["resource"] = 1019,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 7,
	},
	{
		["id"] = 64,
		["typeA"] = 3,
		["resource"] = 1020,
		["word"] = nil,
		["typeB"] = 2,
		["condition"] = 7,
	},
}