TequanReward={
	{
		["id"] = 1,
		["tpyeA"] = 1,
		["name"] = "进阶丹礼包",
		["needVIP"] = 2,
		["cost"] = 120,
		["times"] = 5,
		["fbei"] = 4,
		["tpye1"] = 3,
		["typeid1"] = 0,
		["num1"] = 20,
		["tpye2"] = 4,
		["typeid2"] = 2251,
		["num2"] = 50,
		["tpye3"] = nil,
		["typeid3"] = nil,
		["num3"] = nil,
		["tpye4"] = nil,
		["typeid4"] = nil,
		["num4"] = nil,
		["tpye5"] = nil,
		["typeid5"] = nil,
		["num5"] = nil,
	},
	{
		["id"] = 2,
		["tpyeA"] = 2,
		["name"] = "神器材料包",
		["needVIP"] = 3,
		["cost"] = 120,
		["times"] = 5,
		["fbei"] = 4,
		["tpye1"] = 3,
		["typeid1"] = 0,
		["num1"] = 20,
		["tpye2"] = 4,
		["typeid2"] = 2300,
		["num2"] = 100,
		["tpye3"] = nil,
		["typeid3"] = nil,
		["num3"] = nil,
		["tpye4"] = nil,
		["typeid4"] = nil,
		["num4"] = nil,
		["tpye5"] = nil,
		["typeid5"] = nil,
		["num5"] = nil,
	},
	{
		["id"] = 3,
		["tpyeA"] = 3,
		["name"] = "经验丹礼包",
		["needVIP"] = 4,
		["cost"] = 120,
		["times"] = 5,
		["fbei"] = 4,
		["tpye1"] = 3,
		["typeid1"] = 0,
		["num1"] = 20,
		["tpye2"] = 4,
		["typeid2"] = 2008,
		["num2"] = 100,
		["tpye3"] = nil,
		["typeid3"] = nil,
		["num3"] = nil,
		["tpye4"] = nil,
		["typeid4"] = nil,
		["num4"] = nil,
		["tpye5"] = nil,
		["typeid5"] = nil,
		["num5"] = nil,
	},
	{
		["id"] = 4,
		["tpyeA"] = 4,
		["name"] = "召唤石礼包",
		["needVIP"] = 5,
		["cost"] = 120,
		["times"] = 5,
		["fbei"] = 4,
		["tpye1"] = 3,
		["typeid1"] = 0,
		["num1"] = 20,
		["tpye2"] = 4,
		["typeid2"] = 2302,
		["num2"] = 10,
		["tpye3"] = nil,
		["typeid3"] = nil,
		["num3"] = nil,
		["tpye4"] = nil,
		["typeid4"] = nil,
		["num4"] = nil,
		["tpye5"] = nil,
		["typeid5"] = nil,
		["num5"] = nil,
	},
}